### ISSUE TITLE
Some resources not loaded

### ISSUE THREAD

**Issue by Radigar** [rhargreaves/ff7-ui#1]
Hi!!! First of all say congratulations for the nice mock up of FF7. I'm having some problems to view full of it. When i try to load all in my browser throws some errors:

```
Failed to load resource: the server responded with a status of 404 (Not Found): http://localhost/mock/assets/js/templates.js
Uncaught TypeError: Cannot read property 'ff7-window.hbs' of undefined: ff7.js:118
```

Can you help me with this? Thanks!

**Comment by rhargreaves** [comment]
Sorry - for some reason I only just saw this. I removed the dependency on Handlebars a while back. All that is required now is underscore JS which is automatically included in `assets/js` by running `make build`. Hopefully that helps!
